version: 2

jobs:
  macbuild:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run: bin/fetch-configlet
      - run: bin/configlet lint . --track-id=typescript
      - run: make test

workflows:
  version: 2
  workflow:
    jobs:
      - macbuild
