version: 2

jobs:
  build920:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run: bin/fetch-configlet
      - run: bin/configlet lint . --track-id=typescript
      - run: touch Brewfile; echo "brew 'gnu-sed', args: ['--with-default-names']" >> Brewfile;
      - run: brew bundle
      - run: PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
      - run: make test

workflows:
  version: 2
  workflow:
    jobs:
      - build920
