[a4d7d2f0-ad8a-460c-86f3-88ba709d41a7]
description = "No items"
include = true

[1d39e98c-6249-4a8b-912f-87cb12e506b0]
description = "One item, but too heavy"
include = true

[833ea310-6323-44f2-9d27-a278740ffbd8]
description = "Five items. Can\'t be greedy by weight"
include = true

[277cdc52-f835-4c7d-872b-bff17bab2456]
description = "Five items. Can\'t be greedy by value"
include = true

[81d8e679-442b-4f7a-8a59-7278083916c9]
description = "Example knapsack"
include = true

[f23a2449-d67c-4c26-bf3e-cde020f27ecc]
description = "8 items"
include = true

[7c682ae9-c385-4241-a197-d2fa02c81a11]
description = "15 items"
include = true
