#!/usr/bin/env node

/**
 * Run this script (from root directory): yarn babel-node scripts/lint
 *
 * This runs `eslint` on all sample solutions (and test) files
 */

const shell = require('shelljs')
const {
  registerExitHandler,
  prepareAndRun,
  assignments: exercises,
} = require('./helpers')

registerExitHandler()

const assignment = exercises.length === 0 ? exercises[0] : undefined

// Prepare exercises and cleanup afterwards
shell.env['PREPARE'] = true
shell.env['CLEANUP'] = true

const infoStr = assignment
  ? `Running lint for ${assignment}...`
  : `Running lint for ${exercises.length} exercises...`
const failureStr = '[Failure] Lint check failed!'

// Run lint all at once
prepareAndRun(
  'yarn eslint tmp_exercises --ext .ts --ext .tsx',
  infoStr,
  failureStr
)

shell.echo(
  assignment
    ? `[Success] Lint passed for ${assignment}`
    : `[Success] Lint passed for all ${exercises.length} exercises`
)
