#!/usr/bin/env node

/**
 * Run this script (from root directory): yarn babel-node scripts/sync
 *
 * This script is used to copy the following files to all exercises and keep
 * them in sync:
 *
 * - .eslintignore
 * - .eslintrc
 * - babel.config.js
 * - jest.config.js
 * - package.json
 * - tsconfig.json
 * - yarn.lock
 *
 * There is a CI step which checks that package.json in root & exercises match
 * (see checksum script for more info).
 */

const shell = require('shelljs')
const assignment = shell.env['ASSIGNMENT']
const helpers = require('./helpers')
const path = require('path')

function copyConfigForAssignment(assignment) {
  const destination = path.join('exercises', assignment)
  helpers.COMMON_FILES.forEach((file) => {
    shell.cp(path.join('common', file), path.join(destination, file))
  })
}

if (assignment) {
  shell.echo('Syncing ' + assignment + '...')
  copyConfigForAssignment(assignment)
} else {
  shell.echo('Syncing all assignments...')
  helpers.assignments.forEach(copyConfigForAssignment)
}
