# This workflow will do a fetch the latest configlet binary and lint this repository.

name: configlet

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4

      - name: Fetch configlet
        uses: exercism/github-actions/configlet-ci@main

      - name: Configlet Linter
        run: configlet lint
