# This workflow will do a fetch the latest configlet binary and lint this repository.

name: configlet

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # v2.3.4

      - name: Fetch configlet
        uses: exercism/github-actions/configlet-ci@main

      - name: Configlet Linter
        run: configlet lint
